import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";

import LoadingCounter from "../components/LoadingCounter";
import ImageSequence from "../components/ImageSequence";
import MovieCardSliderSm from "../components/MovieCardSliderSm";
import DistritoCultura from "../components/DistritoCultura";
import Benefit from "../components/Benefit";
import Location from "../components/Location";
import Cards from "../components/Cards";
import HeroSlider from "../components/HeroSlider";
import Promotor from "../components/Promotor";
import Link from "next/link";
import RotateMovieSlider from "@/components/RotateMovieSlider";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

const ctas = [
	{ id: 1, link: "Eventos " },
	{ id: 2, link: "Distrito de cultura " },
	{ id: 3, link: "Cliente " },
	{ id: 4, link: "Ubicación " },
	{ id: 5, link: "Promotores" },
];

export default function Home() {
	return (
		<>
			<Head>
				<title>
					Viveclaro | El primer y más grande espacio verde multipropósito
				</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="header-area bckg-5C0B0C pt-10 pb-10 visibleDesktop">
				<div className="container">
					<div className="d-flex justify-content-between align-items-center">
						<div className="">
							<Image
								src="/images/logotipo-viveclaro-red.webp"
								alt="logo"
								width={200}
								height={56}
							/>
						</div>
						<div className="d-flex align-items-center gap-4">
							{ctas.map((cta) => (
								<Link
									href={`/#section-${cta.id}`}
									scroll={false}
									onClick={(e) => {
										e.preventDefault();
										document
											.getElementById("seccion1")
											?.scrollIntoView({ behavior: "smooth" });
									}}
								>
									{cta.link}
								</Link>
							))}

							<div className="">
								<Link
									href="#"
									className="custom-button custom-button-transparent"
								>
									CONTÁCTENOS
								</Link>
							</div>
						</div>
					</div>
				</div>
			</header>
			<div className="visibleMobile">
				<div className="visibleMobile-logo">  
					<Image
						src="/images/logotipo-viveclaro-red.webp"
						alt="logo"
						width={200}
						height={56}
					/>
					<p>Estamos trabajando para llevarte toda la magia de nuestro espacio verde multipropósito a la palma de tu mano.</p>
				</div>
			</div>
			<div
				className={`visibleDesktop ${geistSans.variable} ${geistMono.variable}`}
			>
				<main>
					<LoadingCounter />
					<ImageSequence />
					<MovieCardSliderSm />
					<DistritoCultura />
					<RotateMovieSlider />
					<Benefit />
					<Location />
					<Cards />
					<HeroSlider />
					<Promotor />
				</main>
				<footer className="footer pt-30 pb-30">
					<div className="container">
						<div className="d-flex justify-content-between align-content-center">
							<div>
								<Image
									src="/images/logotipo-viveclaro-white.png"
									alt="logo"
									width={256}
									height={144}
								/>
							</div>
							<div className="col-md-4">
								<h5 className="">Suscríbete</h5>
								<form>
									<input
										type="email"
										placeholder="Tu correo electrónico"
										className="input"
									/>
									<button className="custom-button">Suscríbete</button>
								</form>
							</div>
							<div className="d-flex align-items-center justify-content-center">
								<Link
									href="mailto:distritoverdecol@email.com"
									className="d-flex gap-3"
								>
									<Image
										src="/images/send.png"
										alt="clock"
										width={30}
										height={30}
									/>
									distritoverdecol@email.com
								</Link>
							</div>
							<div className="d-flex align-items-center justify-content-center">
								<Link href="">
									<span className="d-flex align-items-center gap-3">
										<Image
											src="/images/send.png"
											alt="clock"
											width={30}
											height={30}
										/>
										<div>
											calle 53 #66-19, <br />
											Bogotá D.C Colombia.
										</div>
									</span>
								</Link>
							</div>
						</div>
					</div>
				</footer>
			</div>
		</>
	);
}
